### ISSUE TITLE
Update repository description /about.

### ISSUE THREAD

**Issue by bulak** [Turkish-Bird-Records-Committee/bird_atlas_live_dev#2]
We need to fill in the 'description' and other fields under 'about' section of the repo.

**Comment by keremaliboyla** [comment]
Breeding Bird Atlas' are powerful tools to document the change in natural world, yet they are produced every 10-20 years and need significant human resources and funds and a lot of time. In the age of digital world, people, including atlas volunteers, would like to see the results of their work immediately. The aim of Bird Atlas Live! is to continuously update bird atlas maps with observation data submitted to eBird, the biggest online bird database.
All recent observations of breeding birds will be assigned to atlas squares. This information will be checked against the most recent available atlas data. New information, such as the occurrence of the species in a previously unknown atlas square, will be filtered out, and immediately incorporated to the maps. 
Communication with the observer and immediate feedback to the observer is critical for a bird atlas. Atlas maps will be published on a website and updated weekly. The observer will be informed by direct e-mail about his/her remarkable sighting. The observer will also be encouraged to validate his/her sighting on the map. The maps presenting the level of observer effort might encourage birders to visit least known areas.
The immediate incorporation of observers’ data into the atlas map is crucial to boost volunteer participation, the regional pride for birds and conservation of local bird populations. Maps will be updated every year and will include the information from the past five years.

**Comment by bulak** [comment]
'About' section does not show long text, rather converts into ... and expects user interaction to display the rest. I used parts of the first paragraph for 'about'. The rest we can use within the README.md. If this is OK for you, you can close the issue.
